name: Unique CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.13
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Go-linter
      uses: Jerome1337/golint-action@v1.0.2

    - name: Build Lean Go Binary
      run: go build -o target/unique -v -ldflags="-s -w " mgudmund/unique
      env:
        GOOS: linux
        GOARCH: amd64
        CGO_ENABLED: 0

    - name: Test
      run: go test -v .

    - name: Run ShiftLeft Security Scans
      uses: ShiftLeftSecurity/scan-action@v1.0.0


    # upload artifacts
    - name: Upload ShiftLeft Security Reports
      uses: actions/upload-artifact@v2.1.4
      with:
        name: reports
        path: reports

    - name: Build and push Docker images
      uses: docker/build-push-action@v1
      with:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        registry: docker.pkg.github.com
        repository: mgudmund/unique/unique
        tag_with_ref: true
        tag_with_sha: true





